input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Happy)
    servos.P1.setAngle(-300)
    basic.pause(500)
    servos.P1.setAngle(90)
    basic.pause(200)
    basic.showIcon(IconNames.Heart)
})
basic.showIcon(IconNames.Heart)
servos.P1.setAngle(90)
